// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Logra_API.Models;

public partial class Dia
{
    public int Id { get; set; }

    public int UsuarioId { get; set; }

    public DateTime Fecha { get; set; }

    public string Mood { get; set; }

    public string NotaDia { get; set; }

    public string NotaManiana { get; set; }

    public int AguaConsumida { get; set; }

    public int? HorasSueno { get; set; }

    public string Desayuno { get; set; }

    public string Almuerzo { get; set; }

    public string Cena { get; set; }

    public string Snack { get; set; }

    public virtual ICollection<Tarea> Tareas { get; set; } = new List<Tarea>();

    public virtual Usuario Usuario { get; set; }
}