// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Logra_API.Models;

public partial class LograContext : DbContext
{
    public LograContext(DbContextOptions<LograContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Dia> Dias { get; set; }

    public virtual DbSet<Tarea> Tareas { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Dia>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__dias__3213E83FB23B1E09");

            entity.ToTable("dias");

            entity.HasIndex(e => new { e.UsuarioId, e.Fecha }, "uq_usuario_fecha").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AguaConsumida).HasColumnName("aguaConsumida");
            entity.Property(e => e.Almuerzo)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("almuerzo");
            entity.Property(e => e.Cena)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("cena");
            entity.Property(e => e.Desayuno)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("desayuno");
            entity.Property(e => e.Fecha).HasColumnName("fecha");
            entity.Property(e => e.HorasSueno).HasColumnName("horasSueno");
            entity.Property(e => e.Mood)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("mood");
            entity.Property(e => e.NotaDia)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("notaDia");
            entity.Property(e => e.NotaManiana)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("notaManiana");
            entity.Property(e => e.Snack)
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("snack");
            entity.Property(e => e.UsuarioId).HasColumnName("usuarioId");

            entity.HasOne(d => d.Usuario).WithMany(p => p.Dia)
                .HasForeignKey(d => d.UsuarioId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_dias_usuario");
        });

        modelBuilder.Entity<Tarea>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tareas__3213E83FBB528AEF");

            entity.ToTable("tareas");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false)
                .HasColumnName("descripcion");
            entity.Property(e => e.DiaId).HasColumnName("diaId");
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("fechaCreacion");
            entity.Property(e => e.Realizada).HasColumnName("realizada");

            entity.HasOne(d => d.Dia).WithMany(p => p.Tareas)
                .HasForeignKey(d => d.DiaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_tareas_dia");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__usuarios__3213E83F99FCD151");

            entity.ToTable("usuarios");

            entity.HasIndex(e => e.Email, "UQ__usuarios__AB6E6164889DB4AD").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Apellido)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("apellido");
            entity.Property(e => e.ContraseniaHash)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("contraseniaHash");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.FechaRegistro)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("fechaRegistro");
            entity.Property(e => e.Nombre)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("nombre");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}