// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Logra_API.Models;

public partial class Tarea
{
    public int Id { get; set; }

    public int DiaId { get; set; }

    public string Descripcion { get; set; }

    public bool Realizada { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual Dia Dia { get; set; }
}