// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Logra_API.Models;

public partial class Usuario
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string ContraseniaHash { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public DateTime FechaRegistro { get; set; }

    public virtual ICollection<Dia> Dia { get; set; } = new List<Dia>();
}