// <auto-generated />
using System;
using Logra_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Logra_API.Migrations
{
    [DbContext(typeof(LograContext))]
    partial class LograContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("Logra_API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Logra_API.Models.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Breakfast")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("desayuno");

                    b.Property<string>("DailyNote")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("notaDia");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha");

                    b.Property<string>("Dinner")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("cena");

                    b.Property<string>("Lunch")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("almuerzo");

                    b.Property<string>("Mood")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("mood");

                    b.Property<string>("MorningNote")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("notaManiana");

                    b.Property<int?>("SleepHours")
                        .HasColumnType("INTEGER")
                        .HasColumnName("horasSueno");

                    b.Property<string>("Snack")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("snack");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuarioId");

                    b.Property<int>("WaterIntake")
                        .HasColumnType("INTEGER")
                        .HasColumnName("aguaConsumida");

                    b.HasKey("Id")
                        .HasName("PK__dias__3213E83FB23B1E09");

                    b.HasIndex(new[] { "UserId", "Date" }, "uq_usuario_fecha")
                        .IsUnique();

                    b.ToTable("dias", (string)null);
                });

            modelBuilder.Entity("Logra_API.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("isArchived");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedDate");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("Logra_API.Models.NoteCategory", b =>
                {
                    b.Property<int>("NoteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("noteId");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("categoryId");

                    b.HasKey("NoteId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("noteCategories", (string)null);
                });

            modelBuilder.Entity("Logra_API.Models.TaskCategory", b =>
                {
                    b.Property<int>("TaskItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("taskItemId");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("categoryId");

                    b.HasKey("TaskItemId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("taskCategories", (string)null);
                });

            modelBuilder.Entity("Logra_API.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fechaCreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DayId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("diaId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("realizada");

                    b.HasKey("Id")
                        .HasName("PK__tareas__3213E83FBB528AEF");

                    b.HasIndex("DayId");

                    b.ToTable("tareas", (string)null);
                });

            modelBuilder.Entity("Logra_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("apellido");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("contraseniaHash");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fechaRegistro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("PK__usuarios__3213E83F99FCD151");

                    b.HasIndex(new[] { "Email" }, "UQ__usuarios__AB6E6164889DB4AD")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Logra_API.Models.Category", b =>
                {
                    b.HasOne("Logra_API.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categories_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Logra_API.Models.Day", b =>
                {
                    b.HasOne("Logra_API.Models.User", "User")
                        .WithMany("Days")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_dias_usuario");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Logra_API.Models.Note", b =>
                {
                    b.HasOne("Logra_API.Models.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notes_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Logra_API.Models.NoteCategory", b =>
                {
                    b.HasOne("Logra_API.Models.Category", "Category")
                        .WithMany("NoteCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_noteCategories_category");

                    b.HasOne("Logra_API.Models.Note", "Note")
                        .WithMany("NoteCategories")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_noteCategories_note");

                    b.Navigation("Category");

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Logra_API.Models.TaskCategory", b =>
                {
                    b.HasOne("Logra_API.Models.Category", "Category")
                        .WithMany("TaskCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_taskCategories_category");

                    b.HasOne("Logra_API.Models.TaskItem", "TaskItem")
                        .WithMany("TaskCategories")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_taskCategories_task");

                    b.Navigation("Category");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("Logra_API.Models.TaskItem", b =>
                {
                    b.HasOne("Logra_API.Models.Day", "Day")
                        .WithMany("Tasks")
                        .HasForeignKey("DayId")
                        .IsRequired()
                        .HasConstraintName("fk_tareas_dia");

                    b.Navigation("Day");
                });

            modelBuilder.Entity("Logra_API.Models.Category", b =>
                {
                    b.Navigation("NoteCategories");

                    b.Navigation("TaskCategories");
                });

            modelBuilder.Entity("Logra_API.Models.Day", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Logra_API.Models.Note", b =>
                {
                    b.Navigation("NoteCategories");
                });

            modelBuilder.Entity("Logra_API.Models.TaskItem", b =>
                {
                    b.Navigation("TaskCategories");
                });

            modelBuilder.Entity("Logra_API.Models.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Days");

                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
